### ISSUE TITLE
Export and Import throws error on Windows

### ISSUE THREAD

**Issue by krupenja** [cryham/ccc#1]
Steps:
1. Download Windows release (version 0.9).
2. Extract and run.
3. Press Export or Import.
4. Choose Total Commander in drop-down.

Result:
'Export DC error' or 'Import DC error' is shown. Same if run as Administrator. Also note that error message text is likely incorrect as well (should be 'TC' and not 'DC).

Btw, thank you so much for this project!

**Comment by dimon40001** [comment]
I confirm the issue.

**Comment by cryham** [comment]
This is likely because of wrong path for TC.
If you go on tab "Settings" (or press F3) there is a button
Total Commander - color.ini ...
pressing it will open path pick dialog and then you should find your TC folder and pick color.ini in there.
Or just paste this path into the editbox below the button.
I think I'm not detecting it anyhow so it is probably some bad default not existing path in this case.
